SisGesPro/SisGesPro/urls.py
#from django.contrib import admin
from django.conf.urls import url, include
from django.shortcuts import render

def index(request):
	return render(request, 'index.html')
def mision(request):
	return render(request, 'home/mision.html')
def vision(request):
	return render(request, 'home/vision.html')

urlpatterns = [
    #url(r'^admin/', admin.site.urls),
    url(r'^$', index, name = 'home'),
    url(r'^mision/$', mision, name="mision"),
    url(r'^vision/$', vision, name="vision"),
    url(r'^accounts/', include(('apps.accounts.urls','accounts'), namespace='accounts')),
    url(r'^proyectos/', include(('apps.proyectos.urls','proyectos'), namespace='proyectos')),
]

SisGesPro/apps/accounts/urls.py
from django.conf.urls import url
from django.conf import settings
from django.contrib.auth.views import LoginView, LogoutView, login_required
from . import views
from django.contrib.auth.views import (
    PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
)

urlpatterns = [
    url(r'^$', views.view_counts, name="view_counts"),
    url(r'^login/$', LoginView.as_view(template_name = 'accounts/login.html'), name="login"),
    url(r'^logout/$', LogoutView.as_view(next_page = settings.LOGOUT_REDIRECT_URL), name="logout"),
    url(r'^register/$', views.RegistroUsuario.as_view(), name='register'),
    url(r'^(?P<pk>\d+)/edit/$', login_required(views.UsuarioUpdate.as_view()), name='edit_account'),
    url(r'^profile/$', views.view_profile, name='view_profile'),
    url(r'^profile/edit/$', views.edit_profile, name='edit_profile'),
    #-----------------------------------------------
    url(r'^change-password/$', views.change_password, name='change_password'),
    url(r'^reset-password/$', PasswordResetView, name='reset_password'),
    url(r'^reset-password/done/$', PasswordResetDoneView, name='password_reset_done'),
    url(r'^reset-password/done/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)$', PasswordResetConfirmView, name='password_reset_confirm'),
    url(r'^reset-password/complete/$', PasswordResetCompleteView, name='password_reset_complete')
]

SisGesPro/apps/proyectos/urls.py
from django.conf.urls import url
from django.conf import settings
from django.contrib.auth.views import LoginView, LogoutView, login_required
from . import views
from django.contrib.auth.views import (
    PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
)

urlpatterns = [
    url(r'^$', views.view_proyectos, name='view_proyectos'),
    url(r'^list', views.view_table, name='view_table'),
    url(r'^register/$', views.RegistroProyectos.as_view(), name='register'),
    url(r'^(?P<pk>\d+)/edit/$', login_required(views.EditProyectos.as_view()), name='edit_proyecto'),
    url(r'^(?P<pk>\d+)/productBacklog/$', views.view_product, name='view_product'),
    url(r'^(?P<pk>\d+)/productBacklog/registerUS/$', views.registar_us, name='registerUS'),
    url(r'^(?P<pk>\d+)/productBacklog/(?P<ustory>\d+)/editUS/$', views.editar_us, name='editUS'),
]

SisGesPro/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <style>
            body{position:relative}
            .overlay,.sideMenu{position:fixed;bottom:0}
            .overlay{top:0;left:-100%;right:100%;margin:auto;background-color:rgba(0,0,0,.5);z-index:998;transition:all ease 0.2s}
            .overlay.open{left:0;right:0}
            .sidebarNavigation{margin-bottom:0;z-index:999;justify-content:flex-start}
            .sidebarNavigation .leftNavbarToggler{margin-right:10px;order:-1}
            .sideMenu{left:-100%;top:52px;transition:all ease 0.5s;overflow:hidden;width:100%;z-index:999;max-width:80%;margin-bottom:0;padding:1rem}
            .sideMenu.open{left:0;display:block;overflow-y:auto}
            .sideMenu ul{margin:0;padding:0 15px}
        </style>

        <script>
            window.onload = function(){
                if(window.jQuery){$(document).ready(function(){
                    $(".sidebarNavigation .navbar-collapse").hide().clone().appendTo("body").removeAttr("class").addClass("sideMenu").show();
                    $("body").append("<div class='overlay'></div>");
                    $(".navbar-toggle, .navbar-toggler").on("click",function(){
                        $(".sideMenu").addClass($(".sidebarNavigation").attr("data-sidebarClass"));
                        $(".sideMenu, .overlay").toggleClass("open");
                        $(".overlay").on("click",function(){
                            $(this).removeClass("open");$(".sideMenu").removeClass("open")
                        })
                    });
                    $("body").on("click",".sideMenu.open .nav-item",function(){
                        if(!$(this).hasClass("dropdown")){$(".sideMenu, .overlay").toggleClass("open")}
                    });
                    $(window).resize(function(){
                        if($(".navbar-toggler").is(":hidden")){$(".sideMenu, .overlay").hide()}
                        else{$(".sideMenu, .overlay").show()}
                    })
                })}else{console.log("sidebarNavigation Requires jQuery")}
            }
        </script>
        {% block head %}
        <title>Base</title>
        {% endblock %}
    </head>
    <body>
        <nav class="navbar navbar-expand-md navbar-dark bg-dark sidebarNavigation" data-sidebarClass="navbar-dark bg-dark">
            <div class="container-fluid">
                <h1 class="navbar-brand">SisGesPro</h1>
                <button class="navbar-toggler leftNavbarToggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            
                <div class="collapse navbar-collapse" id="navbarsExampleDefault">
                    <ul class="nav navbar-nav nav-flex-icons ml-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'home' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'mision' %}">Mision</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'vision' %}">Vision</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">RES</a>
                        </li>
                        {% if user.is_authenticated %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ user.nombre }}</a>
                            <div class="dropdown-menu" >
                                <a class="dropdown-item" href="{% url 'accounts:view_profile' %}">Perfil</a>
                                <a class="dropdown-item" href="#">Contraseña</a>
                                <a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a>
                            </div>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link btn-success btn-sm" href="{% url 'accounts:login' %}" role="button">Login</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        {% block Cabecera %}
        {% endblock %}

        {% if user.is_authenticated %}
        <div class="bg-secondary">
            <div class="container">
                <p>
                {% if user.rol == 'A' %}
                <a class="btn btn-info btn-sm" href="{% url 'accounts:view_counts' %}" role="button">Usuarios</a>
                <a class="btn btn-info btn-sm" href="{% url 'proyectos:view_proyectos' %}" role="button">Proyectos</a>
                {% elif user.rol == 'D' %}
                <a class="btn btn-success btn-block" href="#" role="button">Desarrollador</a>
                {% elif user.rol == 'P' %}
                <a class="btn btn-success btn-block" href="#" role="button">ProductOwner</a>
                <a class="btn btn-info btn-sm" href="{% url 'proyectos:view_proyectos' %}" role="button">Proyectos</a>
                {% else %}
                <a class="btn btn-success btn-block" href="" role="button">ScrumMaster</a>
                <a class="btn btn-info btn-sm" href="{% url 'accounts:view_counts' %}" role="button">Usuarios</a>
                <a class="btn btn-info btn-sm" href="{% url 'proyectos:view_proyectos' %}" role="button">Proyectos</a>
                {% endif %}
                </p>
            </div>
        </div>
        {% endif %}
        <div class ="container">
            <div class="col-12">
                {% block body %}
                {% endblock %}
            </div>
        </div>
    </body>
</html>

SisGesPro/templates/index.html
{% extends 'base.html' %}

{% block head %}
<title>Home</title>
{% endblock%}

{% block Cabecera %}
{% if user.is_authenticated %}
<div class="container">
    <h1>{{user.get_rol}}</h1>
    <p>{{ user.nombre }} {{ user.apellido }}, {{ user.correo }}</p>
</div>
 
{% endif %}
{% endblock %}

{% block body %}
<h1>Home</h1>
{% if user.is_authenticated %}
<p>Bienvenido al sistema de gestion de proyectos agiles!</p>
{% else %}
<p>Puedes iniciar sesion aquí</p>
<a href="{% url 'accounts:login' %}">login</a>
{% endif %}

{% endblock%}