SisGesPro/SisGesPro/urls.py
#from django.contrib import admin
from django.conf.urls import url, include
from django.shortcuts import render

def index(request):
	return render(request, 'index.html')
def mision(request):
	return render(request, 'home/mision.html')
def vision(request):
	return render(request, 'home/vision.html')

urlpatterns = [
    #url(r'^admin/', admin.site.urls),
    url(r'^$', index, name = 'home'),
    url(r'^mision/$', mision, name="mision"),
    url(r'^vision/$', vision, name="vision"),
    url(r'^accounts/', include(('apps.accounts.urls','accounts'), namespace='accounts')),
    url(r'^proyectos/', include(('apps.proyectos.urls','proyectos'), namespace='proyectos')),
]

SisGesPro/apps/proyectos/urls.py
from django.conf.urls import url
from django.conf import settings
from django.contrib.auth.views import LoginView, LogoutView, login_required
from . import views
from django.contrib.auth.views import (
    PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
)

urlpatterns = [
    url(r'^$', views.view_proyectos, name='view_proyectos'),
    url(r'^list', views.view_table, name='view_table'),
    url(r'^register/$', views.RegistroProyectos.as_view(), name='register'),
    url(r'^(?P<pk>\d+)/edit/$', login_required(views.EditProyectos.as_view()), name='edit_proyecto'),
    url(r'^(?P<pk>\d+)/productBacklog/$', views.view_product, name='view_product'),
    url(r'^(?P<pk>\d+)/productBacklog/registerUS/$', views.registar_us, name='registerUS'),
    url(r'^(?P<pk>\d+)/productBacklog/(?P<ustory>\d+)/editUS/$', views.editar_us, name='editUS'),
]

SisGesPro/apps/proyectos/models.py
from django.db import models
from apps.accounts.models import Usuario
from django.contrib.postgres.fields import ArrayField, JSONField
from django.shortcuts import render
import django_tables2 as tables
# Create your models here.

class Proyecto(models.Model):
    codigo = models.CharField(
        primary_key = True,
        unique = True,
        max_length = 4,
        blank = True
    )
    nombre = models.CharField(
        max_length = 50
    )
    descripcion = models.TextField(
        max_length=150
    )
    integrantes = models.ManyToManyField(
        Usuario
    )
    fecha_inicio = models.DateField(
        blank = True,
        null = True
    )
    fecha_estimada = models.DateField(
        blank = True,
        null = True
    )
    estado = models.CharField(
        max_length = 1,
        choices = (
            ('1', 'Pendiente'),
            ('2', 'En curso'),
            ('3', 'Cancelado'),
            ('4', 'Terminado'),
            ('5', 'En revision'),
            ('6', 'Aprovado')
        ),
        default = '1'
    )
    fecha_creado = models.DateTimeField(
        auto_now_add = True
    )
    
    class Meta:   
        db_table = 'Proyectos'      
        verbose_name = ('proyecto')
        verbose_name_plural = ('proyectos')

    def __str__(self):
        return self.codigo + ' ' + self.nombre + ' ' + self.estado

    def get_estado(self):
        if self.estado == '1':
            return 'Pendiente'
        elif self.estado == '2':
            return 'En curso'
        elif self.estado == '3':
            return 'Cancelado'
        elif self.estado == '4':
            return 'Terminado'
        elif self.estado == '5':
            return 'En revision'
        else:
            return 'Aprobado'
    
    def get_integrantes(self):
        return self.integrantes

class UserStory(models.Model):
    codigo = models.CharField(
        max_length = 4,
        blank = True
    )
    proyecto = models.CharField(
        max_length = 4,
        blank = True
    )
    nombre = models.CharField(
        unique = True,
        max_length = 30,
        blank = True
    )
    descripcion = models.TextField(max_length = 300, blank=True)
    duracion_estimada = models.IntegerField(blank=True, null=True)
    prioridad = models.CharField(
        max_length = 1,
        choices = (
            ('A', 'Alta'),
            ('M', 'Media'),
            ('B', 'Baja')
        ),
        default = 'B')
    estado = models.CharField(
        max_length = 1,
        choices = (
            ('1', 'Do'),
            ('2', 'Doing'),
            ('3', 'Done')
        ),
        default = '1')
    
    class Meta:  
        db_table = 'UserStorys'      
        verbose_name = ('requisito')
        verbose_name_plural = ('requisitos')
        unique_together = (("codigo", "proyecto"),)
    
    def __str__(self):
        return self.codigo + ' ' + self.nombre + ' ' + self.estado
    
   

SisGesPro/apps/proyectos/forms.py
from django import forms
from .models import Proyecto, UserStory
from django.contrib.auth.forms import UserCreationForm, UserChangeForm 


class RegistroProyectoForm(forms.ModelForm):

	class Meta:
		model = Proyecto
		fields = [                
            'codigo',
            'nombre',
            'descripcion',
            'integrantes',
            'fecha_inicio',
            'fecha_estimada',
        ]

		labels = {
            'codigo':'Codigo',
            'nombre':'Nombre del proyecto',
            'descripcion':'Descripcion',
            'integrantes':'Integrantes',
            'fecha_inicio':'Fecha inicio',
            'fecha_estimada':'Fecha estimada',
		}
       
class EditProyectoForm(forms.ModelForm):
    
    class Meta:
        model = Proyecto
        fields = (
            'codigo',
            'nombre',
            'descripcion',
            'integrantes',
            'fecha_inicio',
            'fecha_estimada',
            'estado',
        )
        labels = {
            'codigo':'Codigo',
            'nombre':'Nombre del proyecto',
            'descripcion':'Descripcion',
            'integrantes':'Integrantes',
            'fecha_inicio':'Fecha inicio',
            'fecha_estimada':'Fecha estimada',
            'estado':'Estado',
		}

        
class RegistroUSForm(forms.ModelForm):

    def __init__(self,*args,**kwargs):
        super(RegistroUSForm, self).__init__(*args, **kwargs)
        self.fields['proyecto'].widget.attrs['readonly'] = True

    class Meta:
        model = UserStory
        fields = [                
            'proyecto',
            'codigo',
            'nombre',
            'descripcion',
        ]
        labels = {
            'proyecto':'Codigo del proyecto',
            'codigo':'Codigo',
            'nombre': 'Nombre del User Story',
            'descripcion':'Descripcion',
		}

        
class EditUSForm(forms.ModelForm):

    class Meta:
        model = UserStory
        fields = [
            'codigo',
            'nombre',
            'descripcion',
        ]
        labels = {
            'codigo':'Codigo',
            'nombre': 'Nombre del User Story',
            'descripcion':'Descripcion',
		}

SisGesPro/apps/proyectos/views.py
from django.shortcuts import render, redirect, reverse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from .models import Proyecto, UserStory
from .forms import RegistroProyectoForm, EditProyectoForm, RegistroUSForm, EditUSForm
from django.urls import reverse_lazy
from .tables import UsTable
from django_tables2.config import RequestConfig
# Create your views here.


def view_proyectos(request):
    return render(request, 'proyectos/lista.html', {
        'proyectos': Proyecto.objects.all()
    })

def view_table(request):
    table = UsTable(UserStory.objects.all())
    RequestConfig(request).configure(table)
    return render(request, 'proyectos/lista_us.html', {'table': table})

def view_product(request, pk):
    return render(request, 'proyectos/product.html', {
        'productBacklog': UserStory.objects.filter(proyecto = pk),
        'proyecto': pk
    })

def registar_us(request, pk):
    if request.method =='POST':
        form = RegistroUSForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request, 'proyectos/product.html', {
                'productBacklog': UserStory.objects.filter(proyecto = pk),
                'proyecto': pk
            })
    else:
        form = RegistroUSForm(initial={'proyecto': pk})
        return render(request, 'proyectos/reg_us.html',  {'form': form})

def editar_us(request, pk=None, ustory=None):
    if request.method == 'POST':
        form = EditUSForm(request.POST, instance=UserStory.objects.get(codigo = ustory, proyecto = pk))
        if form.is_valid():
            form.save()
            return redirect(reverse('proyectos:view_proyectos'))
    else:
        form = EditUSForm(instance=UserStory.objects.get(codigo = ustory, proyecto = pk))
        args = {'form': form}
        return render(request, 'proyectos/edit_us.html', args)


class EditUS(UpdateView):
	model = UserStory
	form_class = EditUSForm
	template_name = 'proyectos/edit_us.html'
	success_url = reverse_lazy('proyectos:view_proyectos')

class RegistroProyectos(CreateView):
	model = Proyecto
	form_class = RegistroProyectoForm
	template_name = 'proyectos/reg_form.html'
	success_url = reverse_lazy('proyectos:view_proyectos')

class EditProyectos(UpdateView):
	model = Proyecto
	form_class = EditProyectoForm
	template_name = 'proyectos/edit_proyecto.html'
	success_url = reverse_lazy('proyectos:view_proyectos')

def edit_profile(request, pk):
    if request.method == 'GET':
	    form = EditProyectoForm(instance= Proyecto.objects.get(codigo=pk))
    else:
        form = EditProyectoForm(request.POST, instance= Proyecto.objects.get(codigo=pk))
        if form.is_valid():
            form.save()
        return redirect('proyectos:view_proyectos')
    return render(request, 'proyectos/editing_proyecto.html', {'form':form})

SisGesPro/templates/proyectos/edit_proyecto.html
{% extends 'base.html' %}

{% block head %}
<title>Editar</title>
{% endblock%}

{% block body %}
<form method="post">
	{% csrf_token %}
	{% load bootstrap %}
    {{ form|bootstrap_horizontal:'col-lg-4' }}

	<button type="submit" class="btn btn-success">Guardar</button>
</form>
{% endblock %}

SisGesPro/templates/proyectos/edit_us.html
{% extends 'base.html' %}

{% block head %}
<title>Editar US</title>
{% endblock %}

{% block body %}
<form method="post">
    {% csrf_token %}
    {% load bootstrap %}
	{{ form|bootstrap_horizontal:'col-lg-4' }}

    <button type="submit" class="btn btn-success">Guardar</button>
</form>

{% endblock %}

SisGesPro/templates/proyectos/lista.html
{% extends 'base.html' %}

{% block head %}
<title>Home</title>
{% endblock%}

{% block body %}
<div class="card mb-5 row">
		
	<div class="card-header col-12">
		<div class="row">
			<div class="text-left col-8"><h2>Proyectos</h2></div>
			<div class="text-right col-2">
				<a class="btn btn-success" href="{% url 'proyectos:register' %}" role="button" >+Agregar</a>
				<a class="btn btn-info" href="{% url 'proyectos:view_table' %}" role="button" >Ver Listado</a>
			</div>
		</div>
	</div>
	
	<div class="card-block p-0 col-12">
		<table class="table table-striped">
			<thead>
				<tr>
					<td>Codigo</td>
					<td>Nombre</td>
					<td></td>
				</tr>
			</thead>
			<tbody>
				{% if proyectos %}
				{% for proyecto in proyectos %}
				<tr>
					<td>{{ proyecto.codigo }}</td>
					<td>{{ proyecto.nombre }}</td>
					<td><a class="btn btn-info" href="{% url 'proyectos:edit_proyecto' proyecto.codigo %}" role="button" >Editar</a></td>
					<td><a class="btn btn-success" href="{% url 'proyectos:view_product' proyecto.codigo %}" role="button">Product Backlog</a></td>
				
				</tr>
				{% endfor %}
				
				{% else %}
				<p>No hay registro de proyectos</p>
				{% endif %}
			</tbody>
		</table>
	</div>
</div>
{% endblock %}

SisGesPro/templates/proyectos/lista_us.html
{# tutorial/templates/tutorial/people.html #}
{% load render_table from django_tables2 %}
<!doctype html>
<html>
    <head>
        <title>Listado de Product Backlog</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
    </head>
    <body>
        {% render_table table %}
    </body>
</html>

SisGesPro/templates/proyectos/product.html
{% extends 'base.html' %}

{% block head %}
<title>Editar</title>
{% endblock%}

{% block body %}
<form method="post">
	<div class="card mb-5 row">
		
		<div class="card-header col-12">
			<div class="row">
				<div class="text-left col-8"><h2>ProductBacklog</h2></div>
				<div class="text-right col-2">
					<a class="btn btn-success" href="{% url 'proyectos:registerUS' pk=proyecto %}" role="button" >+US</a>
				</div>
			</div>
		</div>
		
		<div class="card-block p-0 col-12">
			<table class="table table-striped">
				<thead>
					<tr>
						<td>Codigo</td>
						<td>Nombre</td>
					</tr>
				</thead>
				<tbody>
					{% if productBacklog %}
						{% for us in productBacklog %}
						<tr>
							<td>{{ us.codigo }}</td>
							<td>{{ us.nombre }}</td>
							<td><a class="btn btn-info" href="{% url 'proyectos:editUS' pk=proyecto ustory=us.codigo %}" role="button" >Editar</a></td>
						</tr>
						{% endfor %}
					
					{% else %}
					<p>No hay registro de User Storys</p>
					{% endif %}
				</tbody>
			</table>
		</div>
	</div>
</form>
{% endblock %}

SisGesPro/templates/proyectos/reg_form.html
{% extends 'base.html' %}

{% block head %}
<title>Editar</title>
{% endblock%}

{% block body %}
<form method="post">
	{% csrf_token %}
	{% load bootstrap %}
    {{ form|bootstrap_horizontal:'col-lg-4' }}

	<button type="submit" class="btn btn-success">Guardar</button>
</form>
{% endblock %}

SisGesPro/templates/proyectos/reg_us.html
{% extends 'base.html' %}

{% block head %}
<title>Editar</title>
{% endblock%}

{% block body %}
<form method="post">
	{% csrf_token %}
	{% load bootstrap %}
    {{ form|bootstrap_horizontal:'col-lg-4' }}
	<button type="submit" class="btn btn-success">Guardar</button>
</form>
{% endblock %}