SisGesPro/SisGesPro/urls.py
#from django.contrib import admin
from django.conf.urls import url, include
from django.shortcuts import render

def index(request):
	return render(request, 'index.html')
def mision(request):
	return render(request, 'home/mision.html')
def vision(request):
	return render(request, 'home/vision.html')

urlpatterns = [
    #url(r'^admin/', admin.site.urls),
    url(r'^$', index, name = 'home'),
    url(r'^mision/$', mision, name="mision"),
    url(r'^vision/$', vision, name="vision"),
    url(r'^accounts/', include(('apps.accounts.urls','accounts'), namespace='accounts')),
    url(r'^proyectos/', include(('apps.proyectos.urls','proyectos'), namespace='proyectos')),
]

SisGesPro/apps/accounts/urls.py
from django.conf.urls import url
from django.conf import settings
from django.contrib.auth.views import LoginView, LogoutView, login_required
from . import views
from django.contrib.auth.views import (
    PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
)

urlpatterns = [
    url(r'^$', views.view_counts, name="view_counts"),
    url(r'^login/$', LoginView.as_view(template_name = 'accounts/login.html'), name="login"),
    url(r'^logout/$', LogoutView.as_view(next_page = settings.LOGOUT_REDIRECT_URL), name="logout"),
    url(r'^register/$', views.RegistroUsuario.as_view(), name='register'),
    url(r'^(?P<pk>\d+)/edit/$', login_required(views.UsuarioUpdate.as_view()), name='edit_account'),
    url(r'^profile/$', views.view_profile, name='view_profile'),
    url(r'^profile/edit/$', views.edit_profile, name='edit_profile'),
    #-----------------------------------------------
    url(r'^change-password/$', views.change_password, name='change_password'),
    url(r'^reset-password/$', PasswordResetView, name='reset_password'),
    url(r'^reset-password/done/$', PasswordResetDoneView, name='password_reset_done'),
    url(r'^reset-password/done/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)$', PasswordResetConfirmView, name='password_reset_confirm'),
    url(r'^reset-password/complete/$', PasswordResetCompleteView, name='password_reset_complete')
]

SisGesPro/apps/accounts/models.py
from django.db import models
from django.contrib.auth.models import (
    AbstractBaseUser,
    BaseUserManager
)
# Create your models here.

class UserManager(BaseUserManager):
    #crea y guarda a un usuario con el correo y contraseña dadas
    def create_user(self, correo, password = None):
        if not correo:
            raise ValueError('Los Usuarios deben tener un correo electrónico válido')
        usuario = self.model(correo = self.normalize_email(correo),)
        usuario.set_password(password)
        usuario.save(using = self._db)
        return usuario
    
    #crea y guarda a un usuario super_usuario
    def create_superuser(self, correo, password, ci):
        usuario = self.create_user(correo, password = password, ci= ci)
        usuario.is_superuser = True
        usuario.save(using = self._db)
        return usuario

class Usuario(AbstractBaseUser):
    ci = models.CharField(
        max_length = 8,
        primary_key = True,
        unique = True,
        blank = True,
    )

    correo = models.EmailField(
        max_length = 100,
        blank = True,
        unique = True
    )

    nombre = models.CharField(
        max_length = 30,
        blank = True
    )

    apellido = models.CharField(
        max_length = 30,
        blank = False
    )
    
    telefono =  models.CharField(
        max_length = 12
    )

    sexo = models.CharField(
        max_length = 1,
        choices = (
            ('F', 'Femenino'),
            ('M', 'Masculino')
        ),
        default = 'M'
    )
    
    estado = models.CharField(
        max_length = 1,
        choices = (
            ('A', 'Activo'),
            ('D', 'Despedido'),
            ('J', 'Jubilado'),
            ('R', 'Receso'),
        ),
        default = 'A'
    )

    fecha_creado = models.DateTimeField(
        auto_now_add = True
    )

    is_active = models.BooleanField(
        default = True
    )
    
    is_staff = models.BooleanField(
        default = True
    )

    rol = models.CharField(
        max_length = 1,
        choices = (
            ('A', 'Administrador'),
            ('D', 'Developer'),
            ('P', 'ProductOwner'),
            ('S', 'ScrumMaster'),
        ),
        default = 'A'
    )

    #Establecer manejador del modelo (definido en el siguiente paso)
    object = UserManager()

    USERNAME_FIELD = 'correo'
    REQUIRED_FIELDS = []

    class Meta:
        db_table = 'Usuarios'      
        verbose_name = ('usuario')
        verbose_name_plural = ('usuarios')

    def get_full_name(self):
        return self.nombre +' '+ self.apellido

    def get_short_name(self):
        return self.nombre

    def __str__(self):
        return self.nombre + ' ' + self.apellido + ' ' + self.correo

    def get_rol(self):
        if (self.rol == 'A'):
            return 'Administrador'
        elif (self.rol == 'D'):
            return 'Developer'
        elif (self.rol == 'P'):
            return 'ProductOwner'
        else:
            return 'ScrumMaster'

    

SisGesPro/apps/accounts/forms.py
from django import forms
from .models import Usuario
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


class RegistrationForm(UserCreationForm):

	class Meta:
		model = Usuario
		fields = [
				'ci',
                'nombre',
                'apellido',
                'correo',
                'telefono',
                'sexo',
                'estado',
                'rol',
			]

		labels = {
            'ci': 'Cedula',
            'nombre': 'Nombre',
            'apellido': 'Apellido',
            'correo': 'Correo Electrónico',
            'telefono': 'Telefono',
            'sexo': 'Sexo',
            'estado' : 'Estado',
            'rol': 'Rol'
		}
        

class EditProfileForm(UserChangeForm):
    
    class Meta:
        model = Usuario
        fields = (
            'ci',
            'nombre',
            'apellido',
            'correo',
            'telefono',
            'sexo',
        )

class EditCountForm(UserChangeForm):
    class Meta:
        model = Usuario
        fields = (
            'ci',
            'nombre',
            'apellido',
            'correo',
            'telefono',
            'sexo',
            'estado',
            'rol',
        )

SisGesPro/apps/accounts/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import CreateView
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from .forms import (
    RegistrationForm,
    EditProfileForm,
    EditCountForm
)

from .models import Usuario
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required

class RegistroUsuario(CreateView):
	model = Usuario
	template_name = "accounts/reg_form.html"
	form_class = RegistrationForm
	success_url = reverse_lazy('accounts:view_counts')

class UsuarioUpdate(UpdateView):
	model = Usuario
	template_name = 'accounts/edit_account.html'
	form_class = EditCountForm
	success_url = reverse_lazy('accounts:view_counts')

def view_counts(request):
    return render(request, 'accounts/lista.html', {
        'usuarios': Usuario.object.all()
    })

def view_profile(request, pk = None):
    if pk:
        return render(request, 'accounts/profile.html', {
            'user': Usuario.object.get(pk=pk)
        })
    else:
        return render(request, 'accounts/profile.html', {
            'user': request.user
        })

def edit_account(request, id):
	usuario = Usuario.object.get(ci = id)
	if request.method == 'GET':
		form = EditCountForm(instance = usuario)
	else:
		form = EditCountForm(request.POST, instance = usuario)
		if form.is_valid():
			form.save()
		return redirect('accounts:view_counts')
	return render(request, 'accounts/edit_account.html', {'form':form})

def register(request):
    if request.method =='POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('accounts:home'))

    else:
        form = RegistrationForm()

        args = {'form': form}
        return render(request, 'accounts/reg_form.html',  {
            'form': args
        })
  

def edit_profile(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect(reverse('accounts:view_profile'))
    else:
        form = EditProfileForm(instance=request.user)
        args = {'form': form}
        return render(request, 'accounts/edit_profile.html', args)

def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect(reverse('accounts:view_profile'))
        else:
            return redirect(reverse('accounts:change_password'))
    else:
        form = PasswordChangeForm(user=request.user)

        args = {'form': form}
        return render(request, 'accounts/change_password.html', args)

SisGesPro/templates/accounts/change_password.html
{% extends 'base.html' %}

{% block head %}
<title>Perfiles</title>
{% endblock%}

{% block body %}

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
</form>

{% endblock%}

SisGesPro/templates/accounts/edit_account.html
{% extends 'base.html' %}

{% block head %}
<title>Editar</title>
{% endblock%}

{% block body %}
<form method="post">
	{% csrf_token %}
	{% load bootstrap %}
	{{ form|bootstrap_horizontal:'col-lg-4' }}
	<button type="submit" class="btn btn-success">Guardar</button>
</form>

{% endblock %}

SisGesPro/templates/accounts/edit_profile.html
{% extends 'base.html' %}

{% block head %}
<title>Perfiles</title>
{% endblock %}

{% block body %}
<form method="post">
    {% csrf_token %}

    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="form-group">
                <label >Cedula</label>
                <input class="form-control" type="text" name="ci">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="form-group">
                <label>Nombre</label>
                <input class="form-control" type="text" name="nombre">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="form-group">
                <label >Apellido</label>
                <input class="form-control" type="text" name="apellido">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="form-group">
                <label >Correo Electrónico</label>
                <input class="form-control" type="text" name="correo">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="form-group">
                <label >Telefono</label>
                <input class="form-control" type="text" name="telefono">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="form-group">
                <label >Sexo</label>
                <select class="form-control" type="text" name="sexo">
                    <option value="M">Masculino</option>
                    <option value="F">Femenino</option>
                </select>
            </div>
        </div>
    </div>    
    <button type="submit" class="btn btn-success">Guardar</button>
</form>

{% endblock %}

SisGesPro/templates/accounts/lista.html
{% extends 'base.html' %}

{% block head %}
<title>Home</title>
{% endblock%}

{% block body %}
<div class="card mb-5 row">
		
	<div class="card-header col-12">
		<div class="row">
			<div class="text-left col-8"><h2>Usuarios</h2></div>
			<div class="text-right col-2">
				<a class="btn btn-success" href="{% url 'accounts:register' %}" role="button" >+Agregar</a>
			</div>
		</div>
	</div>
	
	<div class="card-block p-0 col-12">
		<table class="table table-striped">
			<thead>
				<tr>
					<td>Nombre</td>
					<td>Apellido</td>
					<td>Rol</td>
					<td>Accion</td>
				</tr>
			</thead>
			<tbody>
				{% if usuarios %}
				{% for usuario in usuarios %}
				<tr>
					<td>{{ usuario.nombre }}</td>
					<td>{{ usuario.apellido }}</td>
					<td>{{ usuario.get_rol }}</td>
					<td><a class="btn btn-info" href="{% url 'accounts:edit_account' pk=usuario.ci %}" role="button" >Editar</a></td>
				
				</tr>
				{% endfor %}
				
				{% else %}
				<p>No hay registros de usuarios</p>
				{% endif %}
			</tbody>
		</table>
	</div>
</div>

{% endblock%}

SisGesPro/templates/accounts/login.html
{% extends 'base.html' %}

{% block head %}
<title>Login</title>
{% endblock%}

{% block body %}
<form method="POST">
    <main class="login-form">
        <div class="col-12">
            <div class="container">
                <div class="row justify-content-center align-items-center" style="height:70vh">
                    <div class="col-md-8 col-md-offset-3">
                        <div class="card">
                            <div class="card-header">
                                <h2 class="text-center">Login</h2>
                            </div>
                            <div class="card-body">
                                {% csrf_token %}
                                <div class="form-group row">
                                    <label for="email_address" class="col-md-4 col-form-label text-md-right">E-Mail Address</label>
                                    <div class="col-md-6">
                                        <input type="text" class="form-control" name="username" required autofocus>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="password" class="col-md-4 col-form-label text-md-right">Password</label>
                                    <div class="col-md-6">
                                        <input type="password" class="form-control" name="password" required>
                                    </div>
                                </div>
                                
                                <hr>
                                <div class="text-center">
                                    <button type="submit" class="btn btn-lg btn-success">
                                        Login
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>    
    
    </main>
</form>
{% endblock%}

SisGesPro/templates/accounts/profile.html
{% extends 'base.html' %}

{% block head %}
<title>Perfiles</title>
{% endblock%}

{% block body %}

<h1>Usuario</h1>
<p>CI: {{ user.ci }}</p>
<p>Correo: {{ user.correo }} </p>
<p>Nombre: {{ user.nombre }} </p>
<p>Apellido: {{ user.apellido }} </p>
<p>Telefono: {{ user.telefono }} </p>
<p>Sexo: {{ user.sexo }}</p>

{% endblock%} 

SisGesPro/templates/accounts/reg_form.html
{% extends 'base.html' %}

{% block head %}
<title>Register</title>
{% endblock%}

{% block body %}

<form method="post">
    {% csrf_token %}
    {% load bootstrap %}
    {{ form|bootstrap_horizontal:'col-lg-4' }}
    
    <button type="submit" class="btn btn-success">Guardar</button>
</form>
{% endblock%}